platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'example' do
  # Pods for example
  pod 'LineSDK', '~> 5.0.0'

  use_native_modules!
end
